### ISSUE TITLE
Unspecific Specification

### ISSUE THREAD

**Issue by auerswal** [dkogan/vnlog#6]
The vnlog specification does not mention the following points:

* whitespace in front of the first data field (leading whitespace),
* whitespace after the last data field (trailing whitespace),
* comments at the end of a data line (in-line or trailing comments),
* blank lines.
* empty fields (`-`) in the *legend*,
* repeated fields in the *legend*.

I would expect leading and trailing whitespace to be ignored, similar to the field splitting done by Awk.
I would expect blank lines to be ignored, i.e., treated as a (different kind of) comment line.
I would expect that the *legend* must not comprise either empty or repeated labels.

How is vnlog aware software supposed to handle the above?
How does your existing vnlog aware software handle the above?

It would be great if you could add this information to the vnlog specification.

**Comment by auerswal** [comment]
The vnlog support for [GNU Datamash](https://www.gnu.org/software/datamash/) as [merged](https://git.savannah.gnu.org/gitweb/?p=datamash.git;a=commitdiff;h=c38f86e330453cbfab130bcada8380b4b890c5cc) on 2022-08-12 does not recognize trailing comments in the *legend*, only in data lines. My experimental [vnlog to TSV converter](https://github.com/auerswal/junkcode/blob/master/vnlog2tsv.awk) instead supports trailing comments in the *legend*.

It would be awesome if you could specify which behavior is intended for the vnlog format. :-)

**Comment by dkogan** [comment]
Hi.

Currently the tools shipped in the vnlog repo as as permissive as
possible. So even this works:

```
$ cat /tmp/tst.vnl 

# x y # z
bar     5 1 2
bbb     4 7 8


$ < /tmp/tst.vnl vnl-filter -p 's= # + z'

# s
3
15


$ < /tmp/tst.vnl vnl-filter -p '## = # + z'

# ## 
3
15
```

Very weird input is accepted, and I've discovered that people really do
feed it strange data. You can feed it data from the "top" tool, with
column names such as "%CPU" and "TIME+".

I'm hesitant to mandate that all vnlog tools should be this permissive,
though. If I gave somebody's tool data with a column named "#", and that
tool barfed, I wouldn't be surprised at all. I would actually be
expecting this, and I'd be shocked if it DID work. I just tried
datamash: it can't operate on a column named '#'.

So I don't know. If I mandated that "all vnlog tools must support weird
header names", I think this would make it harder to get more tooling
support from others.

Thoughts?

**Comment by auerswal** [comment]
Thanks for looking into this! :-)

That people feed output from existing tools, e.g., `top`, into *vnlog* using tools is a valid reason not to restrict the format too much.  It does seem possible that some output intended for human consumption could use `#…` to indicate a count of something.

I'd say that the *legend* vs. *trailing comment* case is not really obvious.  Perhaps you could add a *considerations* section to the specification where you could list already known corner cases.  

Anyway, `datamash` can sometimes use `#` as column name if it is escaped with a backslash:

    $ printf '# a #\n1 2\n' | ./datamash --vnlog sum '#'
    ./datamash: invalid operand ‘#’
    $ printf '# a #\n1 2\n' | ./datamash --vnlog sum '\#'
    # sum(#)
    2

But not always:

    $ printf '# # a\n1 2\n' | ./datamash --vnlog sum '\#'
    ./datamash: column name ‘#’ not found in input file

I'd assume that to be a `datamash` bug, but have not yet investigated it.

**Comment by dkogan** [comment]
Hi. It's good that datamash kinda supports this, but if it didn't I
wouldn't necessarily say that it doesn't "support vnlog". Since 99% of
people's data wouldn't have "#" fields.

Let me add some format guidelines into the README. Do you think that
would be sufficient?

**Comment by auerswal** [comment]
Hi @dkogan,

yes, I think that adding some format guidelines would help and could be sufficient.

I'd say that adding vnlog support to GNU Datamash has shown that there are a few corner cases that need to be considered when the implementer cannot just use field splitting functions from the programming language (i.e., leading / trailing whitespace and trailing comments). Then there is the difference of support for trailing comments in *data lines*, but not in the *legend*.

Empty lines are not mentioned in the format description either. They seem to be intended to be ignored for calculations, similar to comment lines.

Additionally, there seem to be implicit assumptions regarding the legend contents. Since columns are always addressed by name, the field contents in the legend should better be unique. It also seems that a field with just a `-` in the legend is not really *empty*, but rather named `-`.

I would like a format *specification* to be sufficiently detailed for implementing support for that format, including consistent edge case handling.

As an example, when I first implemented a converter from vnlog to TSV in order to gain an understanding of vnlog, based on the specification I decided that the legend is *syntactically* the same as a data line, except for the leading `#`, i.e., `-` means *empty* and a (second) `#` starts a trailing comment. But that interpretation is different from yours. Thus I think there is some ambiguity in the specification that can be removed by adding a few more words.

Thanks,
Erik

**Comment by auerswal** [comment]
Hi Dima,

according to the GNU Datamash `--vnlog` code and comments, a line comprising a single comment character (`#`), with optional leading and/or trailing whitespace, is ignored as an *empty comment line* while looking for the *legend*.

I think it would be nice if that special case would be documented in the specification, too.

Thanks,
Erik

P.S. I have fixed the above problem with GNU Datamash and a legend of `# # a`.

**Comment by dkogan** [comment]
Hi. I just pushed some documentation and tests that should cover this a bit more extensively. I'm going to close the pull request and the bug. If the update looks incomplete, please feel free to reopen

**Comment by auerswal** [comment]
Looks good, thanks! :-)
